site_name: Notes
site_url:  https://stavros-liaskos.github.io/notes/
site_description: 'A collection of helpfull notes, simple solutions, hacks and things that I stumbled upon'
site_author: 'Stavros Liaskos'

repo_url: https://github.com/stavros-liaskos/notes.git
repo_name: 'Github'

copyright: 'MIT'

strict: true

nav:
  - 'Introduction': 'index.md'
  - 'Notes':
    - 'Apache': 'apacheMac.md'
    - 'Docker': 'docker.md'
    - 'Fail2Ban': 'fail2ban.md'
    - 'Ffmpeg': 'ffmpeg.md'
    - 'Hosts': 'hosts.md'
    - 'ImageMagick': 'imageMagick.md'
    - 'LDAP': 'ldap.md'
    - 'MySQL': 'mysql.md'
    - 'Vagrant': 'vagrant.md'
    - 'Symfony Demo': 'symfony_demo_app.md'
