site_name: Notes
site_url: https://sfa-docs.com
site_description: 'A collection of helpful notes, simple solutions, hacks and things that I stumbled upon'
site_author: 'Stavros Liaskos'

repo_url: https://github.com/stavros-liaskos/notes.git
repo_name: 'Github'

copyright: 'MIT'

strict: true

theme:
  name: 'material'

nav:
  - 'Introduction': 'README.md'
  - 'CSS':
    - 'Selectors': 'css/selectors.md'
    - 'Line Heigh': 'css/line_height.md'
  - 'Notes':
    - 'Apache': 'notes/apacheMac.md'
    - 'Docker': 'notes/docker.md'
    - 'Fail2Ban': 'notes/fail2ban.md'
    - 'Ffmpeg': 'notes/ffmpeg.md'
    - 'Hosts': 'notes/hosts.md'
    - 'ImageMagick': 'notes/imageMagick.md'
    - 'LDAP': 'notes/ldap.md'
    - 'MySQL': 'notes/mysql.md'
    - 'Symfony Demo': 'notes/symfony_demo_app.md'
    - 'Vagrant': 'notes/vagrant.md'
  - 'Scripts':
    - 'Mirror Servers': 'scripts/mirror_gitlab_servers.md'
    - 'Send Backup': 'scripts/sendBackup.md'
    - 'Update Server': 'scripts/update_server.md'
    - 'VagrantDown': 'scripts/vagrantDown.md'
